### PR TITLE
Add elapsed time to gumble_ffmpeg

### PR DESCRIPTION
**Pull request by mathom**
I've been using the elapsed time patch here for stopping/resuming audio streams on my server. I needed to change the integer start offset to float to support fractional seconds to avoid small jumps when you resume audio.

I've also got a patch for [piepan](https://github.com/layeh/piepan) to use this in the javascript plugin: https://github.com/layeh/piepan/pull/28

### CODE REVIEW

**Comment by matthieugrieger** [comment]
This would be a nice addition!

**Comment by bontibon** [comment]
This issue is partially fixed with 0b65794935bac2c4c9e8bb4d56007fd2c7b16e26. I need a little time to look at the elapsed play time (mainly because I think there could be a better solution to calling `time.Since` inside `sourceRoutine`).

**Comment by mathom** [comment]
Great! I'd be interested in seeing an alternative way to track it.

**Comment by bontibon** [comment]
975058a4f8d917c762eb807b902a7eba19e05c52 and 006429f9c4d110e665fc95f675b7a39a69ffc815 should fix this issue.

@mathom The ability to pause streams in piepan will be added soon.

**Pull request closed without merging**
